name: HydraDX-api

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_ACC: ${{ secrets.DOCKERHUB_ACC }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
  ORG: galacticcouncil

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_ACC }}
        password: ${{ env.DOCKERHUB_PASS }}

    - name: Build HydraDX-api
      run: docker build . -t ${{ env.ORG }}/hydradx-api:latest

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.ORG }}/hydradx-api:latest
